### ISSUE TITLE
Add Categories

### ISSUE THREAD

**Issue by CMenne** [UMM-CSci-3601-S18/iteration-4-megabittron#12]

**Comment by john9hoff** [comment]
There is "Business/Career" and "Fun and Recreation" which looks a little awkward. I'd suggest going with one format for multi-categories, preferably & or "and" (not slashes imo, but it isn't a big deal). None of the pictures for your new categories are showing up when I add goals. I can only see health, family, and chores. Is that only on my end?

I think some of the image choices could be improved. I originally had them resized myself because it looks nicer in the assets folder. Its a little weird when family.png is 150px wide then business career.png is 1700px wide. Spiritual, personal development, and romance have white backgrounds but should be transparent. 

Good job on the category choices.
