### ISSUE TITLE
refactor HTML on goals page

### ISSUE THREAD

**Issue by twarling** [UMM-CSci-3601-S18/iteration-4-megabittron#39]

**Comment by Xaivteev** [comment]
Looks good, just removed some unnecessary "this."'s in variable names

**Comment by john9hoff** [comment]
It looks a little messy and a lot of indentation is off. It would be more ideal to put spacing in the CSS rather than having <br> tags everywhere. hide-gt-xs and hide-gt can go in their respective <div> rather than making a <span>. Goals category image heights should go in CSS. A lot of lines of code are very long and could be neatened by hitting enter and breaking it into two lines. There are lots of awkward blank lines. Good job with the class naming.
